### ISSUE TITLE
A complete Documentation on how to use every feature of Kopernicus

### ISSUE THREAD

**Issue by Geoplex-Official** [R-T-B/Kopernicus#12]
^The title^ I could not find a complete doc of Kopernicus anywhere

**Comment by R-T-B** [comment]
The best thing available is the old(ish) Kopernicus Wiki:

https://kopernicus.github.io/wiki/

It was last updated around 1.7.3, though.

This is a valid issue as we REALLY need to start our own docs and update things, so leaving open until we get there to remind me.

**Comment by R-T-B** [comment]
I have temporarily placed a redirect from our "wiki" tab pointing towards the old Kopernicus wiki.  Hopefully this helps with future confusion until proper docs are in place.

Thank you for the report.

**Comment by DeltaDizzy** [comment]
Oh and I would like to add me and democat are still working on the wiki, but going is slow and it is definitely incomplete. It was designed to be able to easily accept pull requests from community members but as of yet none have materialized and the only external contributions have been from a few people sending in txt files with commented nodes.

**Comment by R-T-B** [comment]
I think this can be closed if it's still actively being worked on, we'll just point to you then.  Thanks!
