### ISSUE TITLE
KopernicusExpansion Support

### ISSUE THREAD

**Issue by VabienArt** [R-T-B/Kopernicus#14]
Several utilities from kopernicusexpansion should be updated or merged in to Kopernicus. I've seen that you've been looking in to this on the Forums, and I will be looking in to it as well. Most Updated Version here: https://github.com/StollD/KopernicusExpansion-Continued

**Comment by VabienArt** [comment]
Currently working on Wormhole support. Best I can see the issue with that is the Update void having an undefined variable. 

Also I normally wouldn't put this here, but since you seem to be working on this I put it here. Feel free to close if you aren't planning on using this.

**Comment by VabienArt** [comment]
Going to leave this open, but here's the page I'm using for updates: 
https://github.com/VabienArt/KopernicusExpansion-Continueder/tree/DEV-1.9

**Comment by R-T-B** [comment]
Thanks.  To be clear, over this weekend and into Monday I'm going to be quite busy (family members wedding), but this is absolutely what my branch is intended for and I'll be looking into this as soon as I'm back with eagerness.

**Comment by R-T-B** [comment]
Closing this as you seem to have a handle on it.  Let me know if you need any code merged via PR or forum PM, and I will happily look it over.
