### ISSUE TITLE
Unable to load bodies using the Diffuse scatter shader

### ISSUE THREAD

**Issue by democat3457** [R-T-B/Kopernicus#16]
https://discord.com/channels/365524830667145219/365524831170723844/739212184529141760
Related: prestja/Kopernicus#4 Kopernicus/Kopernicus#449

Seeing multiple occurences happen on the same version, I report this here. (I haven't acually tested it myself, but I'd assume I'd get the same result.)

**Comment by R-T-B** [comment]
It might be the Jool template-rebuilding code going a little too agressive on what it chooses to exclude.  Is this a Jool templated body?

**Comment by democat3457** [comment]
Not that I'm aware, since the body uses LandControl and scatters. (scatter shader Diffuse, not PQS or ScaledVersion shader)

**Comment by R-T-B** [comment]
Ah.  I've no idea what's doing this then.  Does it possibly occur in the old 1.8 build?  I'll tinker with it some later.

**Comment by democat3457** [comment]
I've only seen reports of it happening on 1.10, maybe 1.10 changed something with the shaders.

**Comment by R-T-B** [comment]
Weird.  Will look into it soon.  Thanks for bringing it to my attention.

**Comment by Tequhella** [comment]
Hum... Okay I just deleted LandControl in Izetta.cfg and I have no idea why but it's working. I just followed his instruction : https://forum.kerbalspaceprogram.com/index.php?/topic/187126-17x-eventhorizon-v10-a-blackhole-system-inspired-by-the-movie-interstellar-with-functional-wormholes/&do=findComment&comment=3826936
In fact, I think that Kopernicus has been working properly from the begining. I just didn't do enough research to solve my problems...

**Comment by R-T-B** [comment]
It's still a bug, as the old config should work.  But that is a valid work-around.  Thanks.

**Comment by democat3457** [comment]
> Hum... Okay I just deleted LandControl in Izetta.cfg and I have no idea why but it's working. I just followed his instruction : https://forum.kerbalspaceprogram.com/index.php?/topic/187126-17x-eventhorizon-v10-a-blackhole-system-inspired-by-the-movie-interstellar-with-functional-wormholes/&do=findComment&comment=3826936

It works because LandControl merely adds scatters and provides no gameplay difference. The node isn't required, so that's why removing it doesn't cause errors. However, the planet will look more barren because of the lack of scatters.

**Comment by Tequhella** [comment]
Ah okay, thx ! I'm not sure if I can help, but if you want a file or something that can help you just ask me.

**Comment by R-T-B** [comment]
I've got to be honest, I have no idea what's going on here.  I'm going to leave this open for now, but considering how little the diffuse shader is used, I do not consider this a stopper bug to our CKAN release.  It's going to be filed for now under "known bug, but how to fix?  No idea"

**Comment by R-T-B** [comment]
Nevermind, I think I just figured it out.  Making a bleeding edge release now.

**Comment by R-T-B** [comment]
Fixed.
