### ISSUE TITLE
Gas giants seem desaturated, pale.

### ISSUE THREAD

**Issue by GregroxMun** [R-T-B/Kopernicus#18]
Gas giants in Whirligig World seem pale, as if they've got an extra layer of white in them.
My guess is they're lacking the normal map which Jool used to use, which is why they had the lighting bug before, and the fix to that did _not_ involve adding back the normal map. I verified this behavior in tracking station, map mode, and in-flight.

RTB-Build-15: Shol (at its dimmest--being nearby a double star its brightness fluctuates over time. At its brightest it's washed out and completely white.)
![image](https://user-images.githubusercontent.com/9667986/90274899-648cce00-de2f-11ea-93c7-ae2cbce7b2e1.png)

Old Kopernicus: Shol (medium brightness)

RTB-Build-15: Tyepolbynar
![image](https://user-images.githubusercontent.com/9667986/90275168-d82edb00-de2f-11ea-9d88-d6b7dabf00c3.png)

Old Kopernicus: Tyepolbynar
![image](https://user-images.githubusercontent.com/9667986/90275737-c568d600-de30-11ea-8d14-49961849e0f4.png)

RTB-Build-15: Reander
![image](https://user-images.githubusercontent.com/9667986/90275250-f8f73080-de2f-11ea-8944-d66dd5495d34.png)

Old Kopernicus: Reander
![image](https://user-images.githubusercontent.com/9667986/90276076-4de77680-de31-11ea-97c7-2b8e7d2c1cd0.png)

RTB-Build-15: Mandrake (top) and Rutherford
![image](https://user-images.githubusercontent.com/9667986/90275355-280da200-de30-11ea-9466-84ae3f05c206.png)

Old Kopernicus: Mandrake & Rutherford
![image](https://user-images.githubusercontent.com/9667986/90275767-d285c500-de30-11ea-9dda-fe41ca8ecfda.png)

**Comment by GregroxMun** [comment]
![image](https://user-images.githubusercontent.com/9667986/90278011-aa986080-de34-11ea-876c-e57142d8764a.png)
as evident by Derbin here, the cloudy normal texture is still in the game. This means this can be fixed by modders using the following config (which I am about to test)

```
@ScaledVersion
{                      
          @Material
          {
                        %normals = BUILTIN/cloud_normal
			%bumpMapScale = 15,8
			%bumpMapOffset = 0,0
          }
}
```

**Comment by R-T-B** [comment]
Thanks for the pointers!  I was indeed using just a generic normal map, which I bundled, for gas giants.  This was due to me not knowing the path to the builtin normals.  Now I can finally fix that.  I'll have a release that does so in a moment.

**Comment by R-T-B** [comment]
Fixed in release 17.
