### ISSUE TITLE
AtmosphericStandard scaledversion material type has no support for atmosphere gradients

### ISSUE THREAD

**Issue by GregroxMun** [R-T-B/Kopernicus#19]
Bodies with atmosphere gradients defined by a curve:

```
                ScaledVersion
		{
			Material
			{
				color = 1,1,1,1
				rimPower = 0.7
				rimBlend = 1.5
				Gradient
				{
					//0.0 = 0.45, 0.55, 0.7, 1.0
					0.0 = 0.55,0.55,0.60,1
					0.1 = 0,0,0,1
					0.6 = 0.0,0.0,0.0,1.0
					1.0 = 0.0,0.0,0.0,1.0
				}
			}
			
```

which now use planet templates with the AtmosphericStandard material do not show their atmospheric rims. Workaround is to change all planets using those templates to have atmospheric template, but this might require more work on the part of the planet modder than changing a single line (iirc, changing the scaledspace material requires redefining a few other default features to make things work, but as of typing i haven't tried it yet.)

![image](https://user-images.githubusercontent.com/9667986/90277331-5e005580-de33-11ea-9935-b102c1fca2ab.png)
_Imterril, which should have bright blue atmosphere rims, is naked_

**Comment by democat3457** [comment]
The ``` has to be on a new line iirc

**Comment by R-T-B** [comment]
Is this still a problem in release 16?  I ask because a lot of shader things were bugged in release 15, due to a simple forgotten line of code.

**Comment by R-T-B** [comment]
I need to know if this is still a relevant bug when you get the chance.

**Comment by R-T-B** [comment]
I think this had been fixed for a bit, comment if not.  Release 22+ should have all the fixes to issues like this.
