### ISSUE TITLE
New SolarPanels.cfg break Near Future Solar

### ISSUE THREAD

**Issue by drake127** [R-T-B/Kopernicus#21]
After installing R-T-B dev1101 with new SolarPanels.cfg, it looks like NearFutureSolar mod is broken. When removing SolarPanels.cfg entirely, the problem disappear. Any quick ideas?
```
[LOG 20:21:34.654] PartLoader: Part 'NearFutureSolar/Parts/SolarPanels/deploying-advanced/nfs-panel-deploying-advanced-1x1-ikonos-1/nfs-panel-deploying-advanced-1x1-ikonos-1' has no database record. Creating.
[LOG 20:21:34.654] [DragCubeSystem]: Drag cubes not found or cannot be read for part Part. Generating New drag cubes.
[LOG 20:21:34.655] DragCubeSystem: Creating drag cubes for part 'nfs-panel-deploying-advanced-1x1-ikonos-1'
[WRN 20:21:34.682] Warning on PartSubtype Basic on module ModuleB9PartSwitch (moduleID='cellSwitch') on part nfs-panel-deploying-advanced-1x1-ikonos-1: Could not find matching module
[EXC 20:21:34.685] Exception: Could not find matching module
	B9PartSwitch.ModuleMatcher.FindModule (Part part) (at <b85eabe067044bcb9aeabe863954a5ce>:0)
	B9PartSwitch.ModuleModifierInfo+<CreatePartModifiers>d__10.MoveNext () (at <b85eabe067044bcb9aeabe863954a5ce>:0)
	B9PartSwitch.PartSubtype.Setup (B9PartSwitch.ModuleB9PartSwitch parent, System.Boolean displayWarnings) (at <b85eabe067044bcb9aeabe863954a5ce>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	B9PartSwitch.PartSubtype:Setup(ModuleB9PartSwitch, Boolean)
	B9PartSwitch.ModuleB9PartSwitch:InitializeSubtypes(Boolean)
	B9PartSwitch.ModuleB9PartSwitch:GetInfo()
	PartLoader:CompilePartInfo(AvailablePart, Part)
	<CompileParts>d__56:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

```

**Comment by drake127** [comment]
I tried to use old .cfg and KSP froze on loading of "nfs-panel-deploying-advanced-1x1-ikonos-1.cfg" - the first solar panel of NFS. Either the old Kopernicus solar panel patch didn't work or there's new incompatibility.

**Comment by R-T-B** [comment]
Yeah, this looks more like an issue with b9partswitch.  I run with near future solar as well and don't experience bugs, so rather than replacing or removing the config I'd make sure your b9partswitch is up to date.

If that fails, you can always post back and I'll investigate with you.

**Comment by R-T-B** [comment]
Yeah I just tested my game again and the reason I am not getting your bug is down to my usage of Kerbalism.

This is a b9partswitch issue.  I will make them aware of it.   Leaving open here to track.

**Comment by drake127** [comment]
That's odd. I just deleted all my mods except:
B9PartSwitch 2.17.0
Kopernicus 1.10.1r17
ModularFlightIntegrator (1.2.7 bundled with Kopernicus)
Near Future Solar 1.2.3
ModuleManager 4.1.4

I get the errors right at the start before loading any gamesaves. I am not saying that Kopernicus is to blame but changes in Kopernicus made bug to appear (why?). Also, are you certain you are not getting the bug? So there's problem somewhere else?

**Comment by 7ranceaddic7** [comment]
I'm running 191RC17, upload a KSP.log and I'll compare it with one of mine.

**Comment by drake127** [comment]
[KSP.log](https://github.com/R-T-B/Kopernicus/files/5079038/KSP.log)

**Comment by 7ranceaddic7** [comment]
@R-T-B Can you upload your log too.  I'm getting that EXC too.  Both in 1.9.1 and 1.10.1.
I've been getting it but thought it was something else.  (Wasn't concerned about it because I haven't reached those parts yet.)

**Comment by R-T-B** [comment]
I will upload a log shortly.  We are going through a record breaking heatwave in my hometown right now and lack air conditioning, so computers won't come on until evening.

Note that the solar panel changes between 1.8/the latest 1.9 are not compatible with existing games with flights in progress.  For best results, ground all your flights (you can delete solarpanels.cfg briefly to do so).  Then reinstall the mod as normal.

**Comment by R-T-B** [comment]
As promised, my log and a list of what I was running when I tested it:

[KSP.log](https://github.com/R-T-B/Kopernicus/files/5079930/KSP.log)

<img width="535" alt="list" src="https://user-images.githubusercontent.com/2155778/90325878-f54dd180-df35-11ea-8224-28894d344e71.png">

**Comment by R-T-B** [comment]
Nevermind, the difference was running JNSQ, which aparently suppresses the error somehow.  Most curious.

I now have the same error with your same config.  It is B9Partswitch or near future solar.  I will advise the appropriate devs.

**Comment by R-T-B** [comment]
Fixed in new release #18, we now ship a config patch for this.  Thanks for the report!

**Comment by hemeac** [comment]
@R-T-B, my one concern with the patch as is, is that will only work for Nertea's mods.  While I don't know of any others, I think I have a general solution that should future-proof:

//B9PartSwitch support
@PART:HAS[@MODULE[ModuleB9PartSwitch],~useKopernicusSolarPanels[false]]:FINAL
{
    @MODULE[ModuleB9PartSwitch]
    {
        @SUBTYPE,* // Choose all subtypes
        {
            @MODULE:HAS[@IDENTIFIER[ModuleDeployableSolarPanel]]
            {
                @IDENTIFIER[ModuleDeployableSolarPanel]
                {
                    @name = KopernicusSolarPanels
                }
            }
        }
    }
}

**Comment by R-T-B** [comment]
Thank you, I know I'm no good at modulemanager syntax as I just learned it, hehe.

I will use that version next release, which'll probably be CKAN for stable, and same time for me (sometime monday, we are dealing with a heatwave here that makes operating my computer hard until evening).

**Comment by hemeac** [comment]
Your comment was quite timely as I had just spent Saturday adapting Nertea's solar part switching to stock solar panels.  Definitely test the patch though.  I ran it with the latest Kopernicus bleeding edge with your Nertea patch removed and B9 didn't throw any warnings and the solar panels were charging at the launch pad.  I didn't add any planet packs, so it was just stock planets.

Definitely not a MM expert, but it's been a good challenge to learn.  The syntax is a lot different than the interpretive languages I script in for work.

**Comment by R-T-B** [comment]
Just tested it, works.  Before it gets too hot to run my computer, I spliced the .cfg into existing releases.  No need to make a fuss over it as the old one worked (for now) but I definitely will use your config moving forward.

**Comment by democat3457** [comment]
Lmao @hemeac you just pinged 5 random people in that message, enclose it in ``` and make sure they're on new lines before and after.

**Comment by 7ranceaddic7** [comment]
Just to drop the discussion from a non-related thread...

The only reason I suggested using `:NEEDS[Kopernicus]` is maintaining convention with the intended design.

People do stupid stuff all the time and if you say `:FINAL` it still gets applied.

**Comment by R-T-B** [comment]
Yes, but the final lines are literally just making sure that a Kopernicus config is obeyed.  Anything else would be unintended behavior I think.

**Comment by 7ranceaddic7** [comment]
No, you're fine.

Like I said, `:FINAL` is a conditional best left solely for the end-user _unless absolutely necessary_.

I can get behind the "unintended behavior" aspect.
