### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Massetstephane** [R-T-B/Kopernicus#32]
i have this error with the last version appear in ksp center, repeat continuously : 

`[EXC 18:35:27.898] IndexOutOfRangeException: Index was outside the bounds of the array.
	Kopernicus.Components.ModularScatter.ScatterCollidersComponent.Kopernicus.Components.ModularComponentSystem.IComponent<Kopernicus.Components.ModularScatter.ModularScatter>.Update (Kopernicus.Components.ModularScatter.ModularScatter system) (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	Kopernicus.Components.ModularScatter.ModularScatter.Update () (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 18:35:27.917] IndexOutOfRangeException: Index was outside the bounds of the array.
	Kopernicus.Components.ModularScatter.ScatterCollidersComponent.Kopernicus.Components.ModularComponentSystem.IComponent<Kopernicus.Components.ModularScatter.ModularScatter>.Update (Kopernicus.Components.ModularScatter.ModularScatter system) (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	Kopernicus.Components.ModularScatter.ModularScatter.Update () (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 18:35:27.918] IndexOutOfRangeException: Index was outside the bounds of the array.
	Kopernicus.Components.ModularScatter.ScatterCollidersComponent.Kopernicus.Components.ModularComponentSystem.IComponent<Kopernicus.Components.ModularScatter.ModularScatter>.Update (Kopernicus.Components.ModularScatter.ModularScatter system) (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	Kopernicus.Components.ModularScatter.ModularScatter.Update () (at <6519f4885fc34d929386a1a30a8cf4bc>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

My ksp version is 1.10.1 with french translation and the last version of scatterer (scatterer-0.0632) and (KopernicusBE_1101_Release37)
forget that and the las beyond home mod  (Beyond.Home.1.5.2)

[logfile.zip](https://github.com/R-T-B/Kopernicus/files/5329316/logfile.zip)

**Comment by R-T-B** [comment]
Sorry I did not see this sooner, is this still happening in latest release?

**Comment by R-T-B** [comment]
Assuming fixed in latest release, please reopen if still an issue.
