### ISSUE TITLE
kopernicus incompatibility issue with KSP version 1.10.1.2939

### ISSUE THREAD

**Issue by Tjjuul1996** [R-T-B/Kopernicus#34]
i'm not sure if it's just me not doing it right or something else but I was sent to the link from a Youtube video that was uploaded 2 months ago and followed the steps shown and it still shows as incompatible could it possibly be other mods that are installed causing the issues? i'm using KSP version 1.10.1.29 with the following mods installed not including kopernicus;
- AstronomersVisualPack
- AstronomersVisualPack-1.11
- Environmental Visual Enhancements
- Near Future Props
- Scatterer
- Tarsier Space Tech
- Station Parts Expansion Redux
- Kerbal Engineer Redux
- Modular Flight Integrator
- CommunityTerrainTexturePack
(trying to install Outer planets mod) 
Game seems to work with only Kerbal Engineer, tarsier space tech, scatterer, E.V.E, near future props station parts expansion redux, and both astronomers visual packs  below are screenshots of how all files are placed in game data file
{***EDIT*** files being put in the game data folder as shown stops the incompatibility pop up message from showing but kopernicus and outer planets mods still dont work and causes scatterer to stop functioning correctly} 
![2020-10-21 (1)](https://user-images.githubusercontent.com/73263497/96808197-3c8c8e80-13cd-11eb-9056-fe8f1ef45ecb.png)
![2020-10-21 (2)](https://user-images.githubusercontent.com/73263497/96808200-3f877f00-13cd-11eb-92d1-7c7bd209e470.png)

**Comment by R-T-B** [comment]
Sorry for missing this for so long...

Have you tried downloading the latest 1.10 release from our website instead, ala:

https://github.com/R-T-B/Kopernicus/releases/download/UBE-release-43/KopernicusBE_1101_Release43.zip

**Comment by Tjjuul1996** [comment]
Yes I did and I ended up having to remove all mods then replace them in the
same order as before to make scatter work but still unable to use planet
packs

**Comment by R-T-B** [comment]
Hmmm.  Can I get your logs zip?  It should be in <Install Folder>/Logs/Logs-Kopernicus.zip

**Comment by Tjjuul1996** [comment]
when i open the log files it just gives me 3 options which is 1. game data
2. logs
and a text document labeled KSP

**Comment by Tjjuul1996** [comment]
![2020-11-02](https://user-images.githubusercontent.com/73263497/97927219-6e7ce980-1d19-11eb-9f60-a1e88cc17daa.png)

**Comment by Tjjuul1996** [comment]
my scatterer mod, and visual mods work when my mod files look like this, but any mods or addons applied beyond this causes visual mods to stop working
![2020-11-02](https://user-images.githubusercontent.com/73263497/97927308-9a986a80-1d19-11eb-89f8-6726691e7080.png)

**Comment by Tjjuul1996** [comment]
![2020-11-02 (1)](https://user-images.githubusercontent.com/73263497/97927414-c61b5500-1d19-11eb-89ec-ff3b0908bbe4.png)

**Comment by Tjjuul1996** [comment]
after updating kopernicus it now gives me this warning
![2020-11-02 (4)](https://user-images.githubusercontent.com/73263497/97927896-bcdeb800-1d1a-11eb-97e9-92a1e2f31220.png)

**Comment by R-T-B** [comment]
ok, looking at your folder structure you are much better off than before in terms of being nearly setup correctly.

Can you give me a screenshot of the folder in gamedata "Kopernicus-release-1.9.1-10?"

I just want to understand how you are unpacking Kopernicus as I believe this is an installation error.  If we can deterimine what step you are doing incorrectly, we can probably make this work.

**Comment by Tjjuul1996** [comment]
Absolutely, im taking the game data folder from the kopernicus download and
moving it to game data file in KSP

**Comment by Tjjuul1996** [comment]
here is the contents of the file you asked to see
![2020-11-02 (6)](https://user-images.githubusercontent.com/73263497/97948498-9bdf8c80-1d45-11eb-8eb1-08e8cf9e0911.png)

**Comment by R-T-B** [comment]
You don't download the source files at all, just the release.  Delete that folder with the contents you just showed, it's source files and unnecessary.

**Comment by Tjjuul1996** [comment]
Oh ok that may have been my issue, when I would download it I would
download the source file too ill let you know if it fixes it

**Comment by Fisheiyy** [comment]
im also having the same issue on 2939 i have the right files for kopernicus and get the same errors

**Comment by Fisheiyy** [comment]
[logs.zip](https://github.com/R-T-B/Kopernicus/files/5648473/logs.zip)
here are all the logs

**Comment by Fisheiyy** [comment]
for now i have just removed it because i wanted to play a custom solar system mod but i can wait

**Comment by R-T-B** [comment]
Hello, Fisheiyy, in your case it's a mod conflict with whatever is providing the mini-avc dll.  That is obsolete.  That being said...  I can see from your log files you KSP install is in a "Cracked games" subfolder.  I'm going to assume this is a "try before you buy" type piracy and really encourage you to buy the product since you are apparently enjoying it.

Either way, yeah, I'm going to have to close this issue because the bug really isn't on my end.  Thanks.  If you want further support, please purchase the game and contact me again should the issue trouble you further upon removing the MiniAVC dll file.

**Comment by Fisheiyy** [comment]
> Hello, Fisheiyy, in your case it's a mod conflict with whatever is providing the mini-avc dll. That is obsolete. That being said... I can see from your log files you KSP install is in a "Cracked games" subfolder. I'm going to assume this is a "try before you buy" type piracy and really encourage you to buy the product since you are apparently enjoying it.
> 
> Either way, yeah, I'm going to have to close this issue because the bug really isn't on my end. Thanks. If you want further support, please purchase the game and contact me again should the issue trouble you further upon removing the MiniAVC dll file.

Hey yeah I have cracked the game I really wanted to play it and dont have the steam cash right now will buy if i can great game also thanks for the help no need to expose me like that tho

**Comment by R-T-B** [comment]
> > Hello, Fisheiyy, in your case it's a mod conflict with whatever is providing the mini-avc dll. That is obsolete. That being said... I can see from your log files you KSP install is in a "Cracked games" subfolder. I'm going to assume this is a "try before you buy" type piracy and really encourage you to buy the product since you are apparently enjoying it.
> > Either way, yeah, I'm going to have to close this issue because the bug really isn't on my end. Thanks. If you want further support, please purchase the game and contact me again should the issue trouble you further upon removing the MiniAVC dll file.
> 
> Hey yeah I have cracked the game I really wanted to play it and dont have the steam cash right now will buy if i can great game also thanks for the help no need to expose me like that tho

Did not mean to expose you, just as a modder I can't rule out issues from the crack, ethical issues aside.

**Comment by Fisheiyy** [comment]
> > > Hello, Fisheiyy, in your case it's a mod conflict with whatever is providing the mini-avc dll. That is obsolete. That being said... I can see from your log files you KSP install is in a "Cracked games" subfolder. I'm going to assume this is a "try before you buy" type piracy and really encourage you to buy the product since you are apparently enjoying it.
> > > Either way, yeah, I'm going to have to close this issue because the bug really isn't on my end. Thanks. If you want further support, please purchase the game and contact me again should the issue trouble you further upon removing the MiniAVC dll file.
> > 
> > 
> > Hey yeah I have cracked the game I really wanted to play it and dont have the steam cash right now will buy if i can great game also thanks for the help no need to expose me like that tho
> 
> Did not mean to expose you, just as a modder I can't rule out issues from the crack, ethical issues aside.

Suprisingly i have had no issues with more while it being cracked so i don't think it would affect only kopernicusvwill find miniavc and destroy it
