### ISSUE TITLE
CKAN Reports incompatible with "Modular Flight Integrator"

### ISSUE THREAD

**Issue by Byolock** [R-T-B/Kopernicus#37]
My CKAN reports a conflict with Modular Flight Integrator.
As the manual installation Version contains Modular Flight Integrator, I wanted to ask if this is the expected Behavior.

**Comment by R-T-B** [comment]
It is.  Unfortunately CKAN incorrectly indexes MFI as being incompatabile with 1.10.1 (while it works fine), so until this is corrected we ship our own MFI in the bleeding edge bundle to fool it into allowing install.

It's not perfect but it's the best work around I have.  Remove any MFI you have via CKAN and it should allow you to install properly.

**Comment by Byolock** [comment]
Thanks for your answer. 
That Workaround works fine, till you want to install FAR for example which marks MFI as required, so you have to mark 1.9 Mods as compatible to install with CKAN. This of course then makes it impossible to install Kopernicus 1.10 cause it wants to remove MFI. I've gone with manual install for now and that works fine. I'll just wait till MFI has an official 1.10 release.

**Comment by R-T-B** [comment]
That's actually a pretty good point.

I'll try to get in touch with sarbian and see if he can't update his CKAN data to make this problem go away once and for all, thanks for letting us know.
