### ISSUE TITLE
Any chance this runs on Mac?

### ISSUE THREAD

**Issue by Dushaoan** [R-T-B/Kopernicus#38]
On Version 1.10.1, downloaded the associated version 45 here. 
Unpacked files to the directory as per install instructions.

<img width="480" alt="Screen Shot 2020-11-07 at 12 20 50 AM" src="https://user-images.githubusercontent.com/58267296/98434693-41209a80-208f-11eb-92f6-403287633706.png">
<img width="431" alt="Screen Shot 2020-11-07 at 12 20 58 AM" src="https://user-images.githubusercontent.com/58267296/98434690-3e25aa00-208f-11eb-808f-f36746a544e0.png"> 
<img width="1186" alt="Screen Shot 2020-11-07 at 12 21 35 AM" src="https://user-images.githubusercontent.com/58267296/98434685-3960f600-208f-11eb-8f7c-88ccc7d2364a.png">

I get the Kopernicus failed on startup error on load.
<img width="319" alt="Screen Shot 2020-11-07 at 12 24 10 AM" src="https://user-images.githubusercontent.com/58267296/98434743-92c92500-208f-11eb-87af-7d4be8370f2a.png">

Any ideas? 

Cheers

**Comment by democat3457** [comment]
This should work on Mac, send KSP.log.

**Comment by Dushaoan** [comment]
Actually, I think this error was caused by making a change to minmus' reference body, if I make any change to that value, I get a object invalid failure to the KSP.log on load

**Comment by Dushaoan** [comment]
Thanks for pointing me towards this, I was able to run kopernicus stock, but any changes to the system.cfg end in failure.

**Comment by Dushaoan** [comment]
Alright, I get it now, the default template isn't to be touched. Use patches to make changes, very cool. 
I just remove all planets except for Kerbin. 
Woot. 
Props to the creator, I'm closing the ticket with apologies, very neat interface you've built here.

`@Kopernicus:AFTER[Kopernicus]
{
	!Body[Moho] {}
	!Body[Duna] {}
	!Body[Eve] {}
	!Body[Ike] {}
	!Body[Gilly] {}
	!Body[Mun] {}
	!Body[Minmus] {}
	!Body[Jool] {}
	!Body[Eeloo] {}
	!Body[Laythe] {}
	!Body[Vall] {}
	!Body[Tylo] {}
	!Body[Bop] {}
	!Body[Pol] {}
	!Body[Dres] {}
}
`
