### ISSUE TITLE
White Snow

### ISSUE THREAD

**Issue by GlitterPony12** [R-T-B/Kopernicus#39]
In Beyond  Home mod I have this glitch when I am close to the ground.
[<blockquote class="imgur-embed-pub" lang="en" data-id="a/60Od0Vt" data-context="false" ><a href="//imgur.com/a/60Od0Vt"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>](url)

**Comment by Gameslinx** [comment]
This is not a Kopernicus bug. Read the install instructions - You need Parallax 1.0.1 when using Beyond Home

**Comment by GlitterPony12** [comment]
Thank you very much, sorry for troubling you.
