### ISSUE TITLE
Compatibility issue with TAC Life Support 

### ISSUE THREAD

**Issue by epower53** [R-T-B/Kopernicus#40]
TAC-LS monitoring of unloaded vessel electric charge shows that when Kopernicus is installed, vessel charge is constantly draining. Stock solar panels on the unloaded vessels have no impact on the loss of EC. Without Kopernicus, the vessel behavior is correct and deployed solar panels prevent EC from draining from unloaded vessels. Somehow, there's an interoperability conflict between these two mods that makes it extremely inconvenient to play the game. Having to constantly switch between vessels to allow their panels to charge the batteries is no fun.

**Comment by Phantom775** [comment]
I can +1 this issue

**Comment by TelluriumCrystal** [comment]
I am also seeing this. I opened an issue on the TAC-LS github since this probably needs to get fixed on their end.

**Comment by R-T-B** [comment]
This is due to how Kopernicus handles solar charging.

We are working on a rewrite of the panel code right now.  I would advise deleting Config/SolarPanels.cfg if you are able to work with only single star support as it will disable the glitchy multistar panel code that causes this.

**Comment by R-T-B** [comment]
Does this occur in the latest builds?

**Comment by TelluriumCrystal** [comment]
This does appear to be fixed in the latest build.

**Comment by R-T-B** [comment]
Great news then!  I'll close this, but feel free to comment and/or reopen if any similar issues arise.
