### ISSUE TITLE
Kopernicus Detected as Virus.

### ISSUE THREAD

**Issue by Mathematician23** [R-T-B/Kopernicus#44]
I tried to load KSP and my planet pack did not load. I try again through the game folder itself, same problem. I look at the logs, and I see that Kopernicus failed to load. I delete it and go to reinstall version (KSP 1.10). When downloaded, Windows Defender says "virus detected", and the download fails. I've seen at least 1 other person have this same issue. I do not believe this is a virus, as I've used it plenty of times before. I think a windows update my have caused this.

I just tried to download version 49 instead, and it succeeded. This issue is version 50.

![Kopernicus fail 2](https://user-images.githubusercontent.com/51880171/102279365-42987a80-3ef9-11eb-84e5-e6c5c789aada.PNG)
![Kopernicus fail](https://user-images.githubusercontent.com/51880171/102279366-42987a80-3ef9-11eb-906b-3b7e39980b64.PNG)

**Comment by R-T-B** [comment]
I will see if I can address this, sorry, have been busy last few days.  Only now has this come to my attention.

**Comment by R-T-B** [comment]
This will be fixed in next release (very soon).  It is a false positive, as suspected.

**Comment by Mathematician23** [comment]
I noticed the patch note on release 51, thank you!
