### ISSUE TITLE
Time warp does not respect altitude limits

### ISSUE THREAD

**Issue by xsrvmy** [R-T-B/Kopernicus#45]
I am using GPP (Galileo) with Kopernicus, and it seems like the altitude limits for warping is not working. I can crash into a moon without getting the "time warp limited to x1" message at all until my ship just explodes.

Not sure if this is a problem with Kopernicus or bettertimewarp.

**Comment by vinix38** [comment]
I think those warp restrictions were disabled in one of KSP's major update. Maybe 1.9 or 1.10, but it was in a changelog. It is a stock feature, not a bug.

**Comment by Fisheiyy** [comment]
> I am using GPP (Galileo) with Kopernicus, and it seems like the altitude limits for warping is not working. I can crash into a moon without getting the "time warp limited to x1" message at all until my ship just explodes.
> 
> Not sure if this is a problem with Kopernicus or bettertimewarp.

if you are at 10000x warp and crash into a moon or get lower than like 10k meters its not going to stop you instantly, if you start reentering kerbin @ 50k meters with 10000x warp its not going to stop you crashing

**Comment by xsrvmy** [comment]
@Fisheiyy I can literally time warp at 10x into the moon though, doesn't seem right. The config for time warp limits are there in GPP as far as I can tell.

**Comment by Fisheiyy** [comment]
> @Fisheiyy I can literally time warp at 10x into the moon though, doesn't seem right. The config for time warp limits are there in GPP as far as I can tell.

well its the mun and it has no atmosphere so no reentering i think it wont slow you because of that try duna or some other body with an atmosphere

**Comment by xsrvmy** [comment]
It's not the mun (I'm using GPP)
You are not supposed to be able to warp at all below a certain altitude. Has nothing to do with atmosphere.

**Comment by vinix38** [comment]
I was wrong earlier, changelog of 1.9 says the following:
* Implement new Max Time Warp logic to allow faster warp rates when on rails. This is managed by gamesettings (ORBIT_WARP_MAXRATE_MODE = PeAltitude).
* Implement Limit modifier for altitude based Max Time Warp logic so players can tune when the mode is set to (ORBIT_WARP_MAXRATE_MODE = VesselAltitude).

**Comment by R-T-B** [comment]
Sorry, somehow I missed this until today.

This does seem to be a bug.  I will look into it after comet work is done.
