### ISSUE TITLE
Bleeding Edge CKAN metadata problems

### ISSUE THREAD

**Issue by HebaruSan** [R-T-B/Kopernicus#46]
The homepage goes here if you click on it:

- https://forum.kerbalspaceprogram.com/index.php?/topic/195799-perseverance-rover-replica-challenge/

The 7 should be a 6.

And the version numbers sort wrong. This will break updates, since CKAN always tries to update to the most recent compatible version of each mod, and these verison numbers indicate that this is UBEE_1101_50 rather than UBEE_111_57. The numeric chunks are interpreted as numbers, so 1101 is numerically compared to 111, and the former is larger. UBEE_1110_57 would sort properly.

The most recent should be at the top:

![image](https://user-images.githubusercontent.com/1559108/103028374-3de94d00-451d-11eb-885e-af739e489aa5.png)

Pointed out by @DasSkelett on Discord.

**Comment by R-T-B** [comment]
The version numbers sorting wrong should be a non-issue since it will only take/consider the releases it is compatible with, no?  And Kopernicus is version locked to a single version.

Still, I will fix it.  Also thanks for the pointer on the forum link, it must've been machine replaced by acccident.  I'll check my scripts.

**Comment by HebaruSan** [comment]
The trick is that most users have 1.8–1.11 marked as compatible, because so few mod authors bother to keep their compatibilities completely updated. A user on 1.11 with 1.10 marked as compatible will be "upgraded" to the 1101 releases.

**Comment by R-T-B** [comment]
Should be retroactively fixed now, do advise.  And thanks!

**Comment by HebaruSan** [comment]
Yup, both problems look good now. Thanks for the quick response. :+1:
