### ISSUE TITLE
The new ring shader does not work

### ISSUE THREAD

**Issue by 89Mods** [R-T-B/Kopernicus#47]
How to reproduce:
Add a 'Rings' node to a celestial  body with at least one 'Ring' sub-node and set 'useNewShader = True' inside it. Simplest example of this would be Sarnus from OPM.

Expected behaviour:
A correctly shaded ring appears around the celestial body.

Observed behaviour:
The ring appears, but is coloured solid purple with no shading applied to it.

Notes:
This happened to me in KSP 1.10.1 using the latest release at the time (Release 58). Running a RX470 and Linux Mint 20, so this most likely either a AMD issue or a Linux issue.

**Comment by R-T-B** [comment]
It's a linux/mac specifc issue.  We currently have an OpenGL issue with the ring shader.

blackrack is working on it.  Appologies is all I can offer, in the meantime...  or tell you to use dxvk, but you lose a lot of CPU performance doing that. :/

**Comment by R-T-B** [comment]
This should be fixed in the latest releases.  Please advise.

**Comment by 89Mods** [comment]
I appears to be working fine now, thank you!
