### ISSUE TITLE
"Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process"

### ISSUE THREAD

**Issue by MatiasBD1** [R-T-B/Kopernicus#48]
**KSP**: 1.10.1 Windows 64-bit
**Problem**: Galaxy corrupted and game saves unloadable.
**Relevant Mods Installed:**
- Kopernicus "Bleeding Edge"
- Scatterer
- EVE
- Stock Visual Terrain
- Stock Visual Enhancements

**Following error message will display once game is loaded**: "Kopernicus wasn't able to load the custom planetary system due to an exception in the loading process"
[MM and Kopernicus Logs](https://www.mediafire.com/file/n2hkqfzfy9spmhw/All_other_requested_files.zip/file)
[KSP.log](https://www.mediafire.com/file/djy4jlmze46v1a6/KSP.log/file)
[player.log](https://www.mediafire.com/file/zdv2hy56peiiffi/Player.log/file)

**Comment by R-T-B** [comment]
Sorry I have taken so long to get back to you, I was out with a flulike thing (not covid, but still no fun).

If you still need support, please delete your KSP.log and regenerate it.  That one is nearly 20MBs and outdated, besides.

**Comment by R-T-B** [comment]
Closing due to age.  Reopen if still and issue.
