### ISSUE TITLE
Decoupling lander from parent craft causes lander to spawn in bugged state

### ISSUE THREAD

**Issue by Casmeron** [R-T-B/Kopernicus#49]
I'm having an issue where decoupling a lander from the parent craft makes the lander spawn in a bugged state, breaking the game. I believe this is due to Kopernicus, since I've tested it in non-Kopernicus games with the same craft file and not had the same problem. 

The lander seems to load in a broken volume of space. It has no registered orbital velocity and isn't controllable. 

Switching back to the space center or tracking station makes the lander vanish completely. Going to the astronaut complex shows I no longer have the kerbals who were on board, but they aren't registered as "lost" - they're simply no longer extant. 

Staying focused on the lander and hitting timewarp gives this result: http://prntscr.com/wds8xa with the lander appearing to shoot out of the solar system and then disappearing from the game as above. 

Separating the lander stage while in transit to the Mun causes the lander to lose its orbital velocity and immediately fall back to Kerbin: http://prntscr.com/wdsdmx (note the main stage is still on an intercept course for the Mun.) 

Sending a kerbal on EVA from the lander results in them being unable to move in any direction, as if they are surrounded by 'invisible walls'. The kerbal jetpacks in any direction but stays next to the lander. 

Switching to the parent ship and sending a kerbal on EVA from the parent ship towards the lander is enlightening. The kerbal will go away from the parent ship, but will never get closer to the lander despite jetpacking towards it at full speed. I've included a brief video of this effect here: https://www.youtube.com/watch?v=MRCZWLEpHKs&feature=youtu.be

You can see that Bill Kerman gets further away from the parent ship he started on, but never gets closer to the lander. 

Mod list:
KerbalEngineer
Kopernicus
OPM
OPM - Final Frontier (Neidon)
RemoteTech
TAC Life Support
CommunityResourcePack
CommunityCategoryKit
Community Terrain Textures Pack
ModularFlightIntegrator
Kerbal Operating System

**Comment by Casmeron** [comment]
I've tried removing all TAC Life Support parts from the ship, removing TACLS from the game and then launching the same ship. It works fine now. 

This is super weird so I've really got no other input to offer here. I'll update this issue if I encounter similar bugs with TAC LS removed from the game.

**Comment by R-T-B** [comment]
closing as part of a cleanup, let me know if you can ever replicate without TACLS.
