### ISSUE TITLE
KopernicusBE incompatibility with ClickThroughBlocker (KSP V1.11)

### ISSUE THREAD

**Issue by CG-Matt** [R-T-B/Kopernicus#50]
When trying to load KopernicusBE with ClickThroughBlocker it causes the main menu buttons to not respond to clicking.

Mods installed when this happened:
Squad
Squad Expansion (Both DLCs)
ModularFlightIntegrator (Version provided with KopernicusBE download)
KopernicusBE (Version for KSP 1.11)
ClickThroughBlocker (Latest version for KSP 1.11)

I'm not sure if this is caused by ClickThroughBlocker or CopernicusBE

**Comment by eberkain** [comment]
I am using both those mods without issue. 

Can you post log files?

**Comment by CG-Matt** [comment]
Sorry I don't quite know where the log files are but I think it might just be my KSP im getting random mods not working on one launch of the game and then working the next launch. Sorry to trouble you.

**Comment by R-T-B** [comment]
I've seen this before.  It was isolated to a firespitter.dll file, IIRC.  I have no idea what that does but it causes this issue.

**Comment by R-T-B** [comment]
closing as invalid as I believe an external mod is to blame, but feel free to post logs if that is wrong and I will reopen.
