### ISSUE TITLE
CKAN support

### ISSUE THREAD

**Issue by SunSerega** [R-T-B/Kopernicus#54]
CKAN currently only sees Kopernicus for KSP 1.9.1.
I wanted to post this to their repository, but then I've realized that this is only a fork of the fork of [the official Kopernicus](https://github.com/Kopernicus/Kopernicus).

So I wanted to ask first - is there maybe a reason to not post this to CKAN? Like this being unofficial, or you think it's not good enough yet.

I personally think it should be listed in CKAN anyway so people can install it without going through manual installation.

**Comment by vinix38** [comment]
It is listed in CKAN: you just need to add a repository.
go to options>CKAN options and click "add" in the "metadata repository" box.
Kopernicus BE should be listed there, just select it and add it.

**Comment by SunSerega** [comment]
Ok thx, it works.
