### ISSUE TITLE
Release 81 bugged Kerbal Alarm Clock/Warp Speed

### ISSUE THREAD

**Issue by Fundati** [R-T-B/Kopernicus#57]
Release 81 has caused KAC to over-warp, warping past the alarm. In release 80, this bug isn't there.

I click on the >> on the map screen to warp to Apoapsis (or periapsis). The time warp goes into maximum and warps way past the alarm. This bug seems to be caused by Release 81, as pervious releases don't have this issue. Others have also reported this issue.

Hope this report can help iron it out!

**Comment by R-T-B** [comment]
Hello.  This may be late, but the bleeding edge is currently deprecated with all work focusing on Kopernicus stable.  Please try that.
